dist: trusty
sudo: required

branches:
  only:
    - master
    - develop
    - rc
    - travis-test

services:
  - docker

before_install:
  - apt-get update
  - apt-get install git curl libunwind8 gettext
  - curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?linkid=848738
  - mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
  - ln -s /opt/dotnet/dotnet /usr/local/bin

install:
  - docker build -t netpkg-tool.build docker
  - docker run --name buildvm netpkg-tool.build /bin/bash Recipe
  - docker cp buildvm:/tmp/NET_Pkg/netpkg-tool $TRAVIS_BUILD_DIR/netpkg-tool

script:
  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/phil-harmoniq/ArgTest
  - ./netpkg-tool ArgTest .
  - ArgTest.npk one two thr33 --npk-v four
