dist: trusty
sudo: required

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install realpath dotnet-sdk-2.*

install:
  - $TRAVIS_BUILD_DIR/build-prep.sh
  - dotnet run --project $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR /usr/local/bin

before_script:
  - netpkg-tool --help

script:
  - git clone https://github.com/phil-harmoniq/Hello $TRAVIS_BUILD_DIR/Hello
  - netpkg-tool $TRAVIS_BUILD_DIR/Hello $TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/Hello one two thr33 --npk-v four
  - netpkg-tool $TRAVIS_BUILD_DIR/Hello $TRAVIS_BUILD_DIR --scd
  - $TRAVIS_BUILD_DIR/Hello one two thr33 --npk-v four
  - netpkg-tool $TRAVIS_BUILD_DIR/Hello $TRAVIS_BUILD_DIR -v -n MrMeeseeks --keep
  - $TRAVIS_BUILD_DIR/MrMeeseeks one two thr33 --npk-v four
