dist: trusty
sudo: required

branches:
  only:
    - master
    - develop
    - rc
    - travis-test

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install git curl libunwind8 gettext fuse
  - sudo modprobe fuse
  - sudo usermod -a -G fuse "$(whoami)"
  - sudo curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?linkid=848738
  - sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
  - sudo ln -s /opt/dotnet/dotnet /usr/local/bin

install:
  - docker build -t netpkg-tool.build docker
  - docker run --name buildvm netpkg-tool.build /bin/bash Recipe
  - docker cp buildvm:/usr/local/bin $TRAVIS_BUILD_DIR/netpkg-tool

script:
  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/phil-harmoniq/ArgTest $TRAVIS_BUILD_DIR/ArgTest
  - $TRAVIS_BUILD_DIR/netpkg-tool ArgTest .
  - $TRAVIS_BUILD_DIR/ArgTest.npk one two thr33 --npk-v four
