dist: trusty
sudo: required

branches:
  only:
    - master
    - develop
    - rc
    - travis-test

services:
  - docker

script:
  - docker build -t netpkg-tool.build docker
  - docker run --name buildvm netpkg-tool.build /bin/bash Recipe
  - docker cp buildvm:/tmp/NET_Pkg/netpkg-tool $TRAVIS_BUILD_DIR/netpkg-tool
