dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-sdk-2.*
    - realpath

before_install:
  - $TRAVIS_BUILD_DIR/build-prep.sh

install:
  - dotnet run --project $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR $HOME

before_script:
  - $HOME/netpkg-tool --help

script:
  - git clone https://github.com/phil-harmoniq/Hello $TRAVIS_BUILD_DIR/Hello
  - $HOME/netpkg-tool $TRAVIS_BUILD_DIR/Hello $HOME -v -n Hello.AppImage
  - $HOME/Hello.AppImage one two thr33 --npk-v four
  - $HOME/netpkg-tool $TRAVIS_BUILD_DIR/Hello $HOME --scd --keep -c
  - $HOME/Hello one two thr33 --npk-v four
